FROM twobombs/qrackmin

# add VCL
RUN wget https://mosix.cs.huji.ac.il/vcl/VCL-1.25.tbz && tar -xjf VCL-1.25.tbz
RUN mkdir /var/log/vcl && mkdir /var/log/vcl/etc && mkdir /var/log/vcl/etc/init.d && mkdir /var/log/vcl/usr && mkdir /var/log/vcl/usr/bin && mkdir /var/log/vcl/etc/rc0.d && mkdir /var/log/vcl/etc/rc1.d && mkdir /var/log/vcl/etc/rc2.d  &&  mkdir /var/log/vcl/etc/rc3.d && mkdir /var/log/vcl/etc/rc4.d &&  mkdir /var/log/vcl/etc/rc5.d &&  mkdir /var/log/vcl/etc/rc6.d 

# setup & install binaries manual 
RUN mkdir /usr/lib/vcl /etc/vcl
RUN cd vcl-1.25 && cp vcl /etc/init.d/vcl && cp vclconf /sbin/vclconf && cp opencld /sbin/opencld && cp broker /sbin/broker && cp libOpenCL.so /usr/lib/vcl/libOpenCL.so && cp vclrun /usr/bin/vclrun && cp supercl.h /usr/include/supercl.h
RUN touch /etc/vcl/is_back_end

EXPOSE 255
ENTRYPOINT /root/run-vcl
