#!/bin/bash
# massively multithreaded qbdd fc range check
# requirements are server node level specs

# enable lightcone
export QRACK_QTENSORNETWORK_THRESHOLD_QB=1
# no statevector, just qbdd
export QRACK_QBDT_HYBRID_THRESHOLD=2
cd /pyqrack-examples/qbdd

for i in {5..36}; do
 for (( d=4; d <= i; d++ )); do
    echo number of qubits $i depth $d
    python3 qbddrp_fc.py 0 $i $d 2>>errors_fc.txt 1>>qbdd_fc_0_$(echo $i).txt &
    sleep 1
 done
done
