#!/bin/bash

# enable lightcone
export QRACK_QTENSORNETWORK_THRESHOLD_QB=1
# no statevector, just qbdd
export QRACK_QBDT_HYBRID_THRESHOLD=2

cd /pyqrack-examples/qbdd

for i in {1..9}; do
 for (( d=4; d <= 6; d++ )); do
    echo 2019 at 52 iteration at depth $d and sep i$

    export QRACK_QBDT_SEPARABILYTY_THRESHOLD=0.000$i
    python3 qbdd_sycamore_2019.py $d 2>>errors_qbdd_sycamore_2019.txt 1>>qbdd_sycamore_2019_$(echo $d).txt &
    sleep 1

  done
done
