#!/bin/bash

# start vcl controller with nodes file from mount
cp /var/log/vcl/etc/vcl/nodes /etc/vcl/nodes

# start vcl backend and controller and precompile all qrack kernels
cd /vcl-1.25/ && ./vcl start && ./vclrun /qrack/_build/qrack_cl_precompile &

# log clinfo
./vclrun clinfo

tail -f /dev/null
