#!/bin/bash
# massively multithreaded qbdd 49 qubit nn odd orbifold range check
# requirements are server node level specs

# replace 'pyQrack engine' for 64+ qubits operations
cd /qrack64/_build && make install

# enable lightcone
export QRACK_QTENSORNETWORK_THRESHOLD_QB=1
# no statevector, just qbdd
export QRACK_QBDT_HYBRID_THRESHOLD=2
cd /pyqrack-examples

for i in {64..64}; do
 for (( d=4; d <= i; d++ )); do
    echo number of qubits $i depth $d
    python3 qbddrp_nn_odd_orbifold.py 0 $i $d 2>>errors_64_nn_odd_orbifold.txt 1>>qbdd_64_nn__odd_orbifold_0_$(echo $i).txt &
    sleep 1
 done
done

for i in {81..81}; do
 for (( d=4; d <= i; d++ )); do
    echo number of qubits $i depth $d
    python3 qbddrp_nn_odd_orbifold.py 0 $i $d 2>>errors_81_nn_odd_orbifold.txt 1>>qbdd_81_nn__odd_orbifold_0_$(echo $i).txt &
    sleep 1
 done
done

