#!/bin/bash
#
# after deployment of the backend nodes
# we now scrape the IPs of the nodes
# deploy the host container and drop into bash
#

echo "" > ips.txt

docker ps -q > containers

while read p
do
    docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $p >>ips.txt
done <containers

# declare nodes for host node
cat ips.txt > /var/log/vcl/etc/vcl/nodes
cat ips.txt
echo where added to the vcl backend IP list

# start host node
echo starting host node, then enter container with shell session for interactive session

docker run --gpus all --device=/dev/dri:/dev/dri --mount type=bind,source=/var/log/vcl,target=/var/log/vcl -d twobombs/qrackmin:vcl-controller > host
docker exec -ti $(<host) bash
