#!/bin/bash
# massively multithreaded qbdd range check
# requirements are server node level specs

cd pyqrack-examples

for i in {5..32}; do
 for (( d=4; d <= i; d++ )); do
    echo number of qubits $i depth $d
    python3 qbddrp_nn.py 0 $i $d 2>errors_$(echo $i)_$(echo $d).txt 1>qbdd_$(echo $i)_$(echo $d).txt &
 done
done
