#!/bin/bash
# massively multithreaded qbdd nn odd orbifold range check
# requirements are server node level specs

# enable lightcone
export QRACK_QTENSORNETWORK_THRESHOLD_QB=1
# no statevector, just qbdd
export QRACK_QBDT_HYBRID_THRESHOLD=2
cd /pyqrack-examples

for i in {1..30}; do
 for (( d=4; d <= 7; d++ )); do
    echo iteration $i at depth $d
    python3 qbddrp_sycamore_2019.py 0 $d 2>>errors_qbddrp_sycamore_2019.txt 1>>qbddrp_sycamore_2019_$(echo $d).txt &
    sleep 1
 done
done
