FROM nvidia/cuda:12.4.1-devel-ubuntu22.04
LABEL com.nvidia.volumes.needed="nvidia_driver"
ENV PATH /usr/local/nvidia/bin:${PATH}
ENV LD_LIBRARY_PATH /usr/local/nvidia/lib:/usr/local/nvidia/lib64:${LD_LIBRARY_PATH}

# install features
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive && apt-get -y install git python3-full python3-pip python3-pybind11 build-essential cmake clinfo openssh-server wget vim-common python3-setuptools opencl-headers curl libfreetype6-dev autotools-dev libicu-dev libbz2-dev libboost-all-dev && apt-get clean all

# clone repos
RUN git clone --recursive --depth=1 --recursive https://github.com/unitaryfund/qrack.git
RUN git clone --recursive --depth=1 --recursive https://github.com/unitaryfund/pyqrack.git

# pyqrack examples integration 
RUN git clone --recursive  --depth=1 https://github.com/vm6502q/pyqrack-examples.git

# pennylane integration code
RUN git clone --recursive --depth=1 --recursive https://github.com/unitaryfund/pennylane-qrack.git
RUN git clone --recursive --depth=1 --recursive https://github.com/PennyLaneAI/pennylane.git

# NVidia hw integration
RUN mkdir -p /etc/OpenCL/vendors && echo "libnvidia-opencl.so.1" > /etc/OpenCL/vendors/nvidia.icd

# Qrack install & dependancies without OpenCL for CPU only processing
RUN cp -r /qrack /qrackcpu
RUN cd /qrackcpu/include && mkdir CL && cd /qrackcpu && mkdir _build && cd _build && cmake -DENABLE_DEVRAND=ON -DFPPOW=5 -DUINTPOW=6 -DQBCAPPOW=6 -DENABLE_COMPLEX_X2=ON -DENABLE_OPENCL=OFF .. && make -i -k -j 2 all && make install

# install PyQrack
RUN cd /pyqrack &&  pip3 install .  && pip3 cache purge

# install dask
RUN pip3 install dask-cuda cupy joblib matplotlib && pip3 cache purge

# install openmpi
RUN apt-get install -y infiniband-diags ibverbs-utils libibverbs-dev libfabric1 libfabric-dev libpsm2-dev
RUN apt-get install -y openmpi-bin openmpi-common libopenmpi-dev libgtk2.0-dev
RUN apt-get install -y librdmacm-dev libpsm2-dev

# install pennylane, openfermion and other dependancies for pyqrack vqe benchmark scripts
RUN apt install -y libopenblas-dev && apt clean all
RUN pip install --prefer-binary --upgrade pyscf && pip cache purge
RUN pip install --prefer-binary --upgrade pennylane pennylane-qrack openfermion openfermionpyscf pennylane-qchem pennylane-cirq cirq matplotlib autograd && pip cache purge

# isntall qiskit for pyqrack-examples ising model interaction
RUN pip install qiskit && pip cache purge

# Qrack install & dependancies 
RUN cd /qrack/include && mkdir CL && cd /qrack && mkdir _build && cd _build && cmake -DENABLE_DEVRAND=ON -DFPPOW=5 -DUINTPOW=6 -DQBCAPPOW=6 -DENABLE_COMPLEX_X2=ON .. && make -i -k -j $(grep -c ^processor /proc/cpuinfo) all  && make install

COPY run-scripts/run* /root/
RUN chmod 755 /root/run*

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES graphics,utility,compute

ENTRYPOINT /root/run
