FROM ubuntu:latest

RUN apt update && apt install -y wget unzip curl && apt clean all
RUN wget https://github.com/unitaryfund/qrack/releases/download/vm6502q.v8.20.1/qrack_Ubuntu_22.04_LTS_benchmarks && chmod 744 qrack_Ubuntu_22.04_LTS_benchmarks
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" &&  unzip awscliv2.zip  && ./aws/install && ./usr/local/bin/aws --version

ENTRYPOINT ./qrack_Ubuntu_22.04_LTS_benchmarks
