FROM twobombs/qrackmin:python

RUN pip3 install git+https://github.com/qulacs/qulacs.git
RUN git clone --depth=1 --recursive https://github.com/Qiskit/qiskit.git

RUN cd /qiskit/docs/tutorials/circuits && jupyter nbconvert --to script *.ipynb
RUN cd /qiskit/docs/tutorials/circuits_advanced && jupyter nbconvert --to script *.ipynb

ENTRYPOINT /run-python
