FROM ubuntu:latest

# install features
RUN apt-get update && apt-get -y install git python3-pip build-essential cmake openssh-server wget vim-common python3-setuptools opencl-headers curl libfreetype6-dev autotools-dev libicu-dev libbz2-dev libboost-all-dev && apt-get clean all

# clone repos
RUN git clone --depth=1 --recursive https://github.com/unitaryfund/qrack.git
RUN git clone --depth=1 --recursive https://github.com/unitaryfund/pyqrack.git
RUN git clone --depth=1 --recursive https://github.com/vm6502q/Eratosthenes


# Qrack install & dependancies without OpenCL for CPU only processing
RUN cd /qrack/include && mkdir CL && cd /qrack && mkdir _build && cd _build && cmake -DENABLE_DEVRAND=ON -DFPPOW=5 -DUINTPOW=6 -DQBCAPPOW=6 -DENABLE_COMPLEX_X2=ON -DENABLE_OPENCL=OFF .. && make -i -k -j 2 all && make install

# install PyQrack
RUN cd /pyqrack &&  pip3 install .

# install Eastothenes
RUN cd /Eratosthenes && pip3 install .

ENTRYPOINT /qrack/_build/benchmarks --optimal-cpu
