FROM ubuntu:latest

# install git,jupyter,python+pip and opencl pocl cpu stub
RUN apt update && apt install -y git python3-pip pocl-opencl-icd && apt clean all
RUN pip3 install --upgrade pip

# install build features
RUN apt-get update && apt-get -y install git build-essential cmake openssh-server wget vim-common python3-setuptools opencl-headers curl libfreetype6-dev autotools-dev libicu-dev libbz2-dev libboost-all-dev && apt-get clean all

# clone repos
RUN git clone --depth=1 --recursive https://github.com/unitaryfund/qrack.git
RUN git clone --depth=1 --recursive https://github.com/unitaryfund/pyqrack.git

# Qrack install & dependancies without OpenCL for CPU only processing
RUN cd /qrack/include && mkdir CL && cd /qrack && mkdir _build && cd _build && cmake -DENABLE_DEVRAND=ON -DFPPOW=5 -DUINTPOW=6 -DQBCAPPOW=6 -DENABLE_COMPLEX_X2=ON -DENABLE_OPENCL=OFF .. && make -i -k -j 2 all && make install

# install PyQrack
RUN cd /pyqrack && ./package.sh && mkdir /usr/local/lib/python3.10/dist-packages/pyqrack && cp -r pyqrack/* /usr/local/lib/python3.10/dist-packages/pyqrack

# fetch pycrack jupyter repo and convert to python 
RUN pip3 install jupyter jupytext 
RUN git clone --depth=1 https://github.com/vm6502q/pyqrack-jupyter.git 
RUN cd pyqrack-jupyter && jupyter nbconvert --to script *.ipynb

# set defailt entrypoint 
COPY run-scripts/run-python /run-python
RUN chmod 744 run-python
ENTRYPOINT /run-python
