FROM nvidia/cuda:12.2.2-devel-ubuntu22.04
LABEL com.nvidia.volumes.needed="nvidia_driver"

ENV PATH /usr/local/nvidia/bin:${PATH}
ENV LD_LIBRARY_PATH /usr/local/nvidia/lib:/usr/local/nvidia/lib64:${LD_LIBRARY_PATH}

# install git, python+pip and pip aws braket sdk
RUN apt update && apt install -y git python3-pip && apt clean all

RUN pip3 install --upgrade pip
RUN pip3 install amazon-braket-sdk qiskit pyqrack-cuda packaging

# install build features
RUN apt-get update && apt-get -y install git build-essential cmake openssh-server wget vim-common python3-setuptools opencl-headers curl libfreetype6-dev autotools-dev libicu-dev libbz2-dev libboost-all-dev && apt-get clean all

# clone repos with qrack and providers
RUN git clone --depth=1 --recursive https://github.com/unitaryfund/qrack.git
RUN git clone --depth=1 https://github.com/vm6502q/qiskit-qrack-provider.git
RUN git clone --depth=1 https://github.com/vm6502q/cirq-qrack.git

# fetch aws braket sim repos and Qrack BraKET backend repo
RUN git clone --depth=1 https://github.com/amazon-braket/amazon-braket-default-simulator-python.git
RUN git clone --depth=1 https://github.com/amazon-braket/amazon-braket-containers.git
RUN git clone --depth=1 https://github.com/amazon-braket/amazon-braket-sdk-python.git
RUN git clone --depth=1 https://github.com/amazon-braket/amazon-braket-examples.git

RUN git clone --depth=1 https://github.com/vm6502q/amazon-braket-qrack-simulator-python.git

# install qrack braket simulator + qiskit & cirq qrack-provider
RUN cd /qiskit-qrack-provider &&  pip3 install .
RUN cd /cirq-qrack &&  pip3 install .
RUN cd /amazon-braket-qrack-simulator-python && pip3 install .

ENV SAGEMAKER_PROGRAM /amazon-braket-qrack-simulator-python/src/braket/qrack_simulator/qrack_simulator.py
ENTRYPOINT python3 /amazon-braket-qrack-simulator-python/src/braket/qrack_simulator/qrack_simulator.py
