FROM ubuntu:latest

# fetch dependancies
RUN apt update && apt install -y wget unzip curl ocl-icd-opencl-dev && apt clean all

# fetch precompiled qrack benchmarks app
RUN wget https://github.com/unitaryfund/qrack/releases/download/vm6502q.v8.20.1/qrack_Ubuntu_22.04_LTS_benchmarks && chmod 744 qrack_Ubuntu_22.04_LTS_benchmarks

# fetch & install aws tools
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" &&  unzip awscliv2.zip  && ./aws/install && ./usr/local/bin/aws --version

# setup qrack benchmarks test
COPY run-scripts/run-aws /run-aws
RUN chmod 744 run-aws && mkdir /var/log/qrack

# set defailt entrypoint 
ENTRYPOINT /run-aws
