FROM nvidia/cuda:12.2.2-devel-ubuntu22.04
LABEL com.nvidia.volumes.needed="nvidia_driver"

RUN wget https://github.com/unitaryfund/qrack/releases/download/vm6502q.v9.7.0/qrack_mac_benchmarks

ENV PATH /usr/local/nvidia/bin:${PATH}
ENV LD_LIBRARY_PATH /usr/local/nvidia/lib:/usr/local/nvidia/lib64:${LD_LIBRARY_PATH}

COPY run-scripts/run /root/run-arm
RUN chmod 744 /root/run-arm

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES graphics,utility,compute
ENTRYPOINT /root/run-arm
