FROM twobombs/qrackmin:latest

# upgrade image because of nv not upgrading
RUN apt update && apt -y upgrade && apt clean all

# fetch cuquantum
RUN apt install -y git cuquantum cuquantum-dev libcutensor1 libcutensor-dev libcutensor-doc && apt clean all
RUN git clone --depth=1 https://github.com/NVIDIA/cuQuantum.git

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES graphics,utility,compute
ENTRYPOINT /root/run
