FROM nvidia/cuda:12.4.1-devel-ubuntu22.04
LABEL com.nvidia.volumes.needed="nvidia_driver"

ENV PATH /usr/local/nvidia/bin:${PATH}
ENV LD_LIBRARY_PATH /usr/local/nvidia/lib:/usr/local/nvidia/lib64:${LD_LIBRARY_PATH}

# upgrade image because of nv not upgrading
RUN apt update && apt -y upgrade && apt clean all

# install dask
RUN apt install -y python3-pip && apt clean all && pip3 install dask-cuda cupy joblib matplotlib && pip3 cache purge

# install openmpi
RUN apt-get install -y infiniband-diags ibverbs-utils libibverbs-dev libfabric1 libfabric-dev libpsm2-dev && apt clean all
RUN apt-get install -y openmpi-bin openmpi-common libopenmpi-dev libgtk2.0-dev && apt clean all
RUN apt-get install -y librdmacm-dev libpsm2-dev && apt clean all
# openmpi benchmark
RUN git clone https://github.com/forresti/osu-micro-benchmarks.git && cd osu-micro-benchmarks 
## && ./configure CC=mpicc CXX=mpicxx --enable-cuda && make

# GVirtuS
RUN apt-get install -y build-essential cmake libxmu-dev libxi-dev libgl-dev libosmesa-dev git liblog4cplus-dev cudnn && apt clean all
RUN git clone https://github.com/vm6502q/GVirtuS.git qrack_update && cd /qrack_update && mkdir build && cd build && cmake .. && make && make install

# fetch thereminq & run/build scripts
RUN git clone --depth=1 https://github.com/twobombs/thereminq.git && cd /thereminq/runscripts/ && chmod 744 * && cp run-* /root/

COPY run-scripts/run* /root/
RUN chmod 755 /root/run*

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES graphics,utility,compute
ENTRYPOINT /root/run
