FROM twobombs/qrackmin

# vm6502q/qimcifa has an LGPL license. Report (re)use of code to Dan Strano
# RUN git clone --depth=1 https://github.com/vm6502q/qimcifa.git && mv qimcifa qimcifa64 && cd /qimcifa64 && cmake -DBIG_INT_BITS=64 . && make

# 128+ qimcifa with loadbalancer
RUN git clone --depth=1 https://github.com/vm6502q/qimcifa.git && mv qimcifa qimcifa128 && cd /qimcifa128 && cmake -DBIG_INT_BITS=128 . && make
RUN git clone --depth=1 https://github.com/vm6502q/qimcifa.git && mv qimcifa qimcifa512 && cd /qimcifa512 && cmake -DBIG_INT_BITS=512 . && make
RUN git clone --depth=1 https://github.com/vm6502q/qimcifa.git && mv qimcifa qimcifa1024 && cd /qimcifa1024 && cmake -DBIG_INT_BITS=1024 . && make

# 128+ qimcifa with RND dispatcher
RUN git clone --depth=1 https://github.com/vm6502q/qimcifa.git && mv qimcifa qimcifa128rnd && cd /qimcifa128rnd && cmake -DBIG_INT_BITS=128 -DIS_RANDOM=ON . && make
RUN git clone --depth=1 https://github.com/vm6502q/qimcifa.git && mv qimcifa qimcifa512rnd && cd /qimcifa512rnd && cmake -DBIG_INT_BITS=512 -DIS_RANDOM=ON . && make
RUN git clone --depth=1 https://github.com/vm6502q/qimcifa.git && mv qimcifa qimcifa1024rnd && cd /qimcifa1024rnd && cmake -DBIG_INT_BITS=1024 -DIS_RANDOM=ON . && make

# old bigint build
RUN git clone --depth=1 --branch opencl_bigint https://github.com/vm6502q/qimcifa.git && mv qimcifa qimcifa-bigint && cd qimcifa-bigint && cmake . && make

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES graphics,utility,compute
ENTRYPOINT /root/run
