FROM nvidia/cuda:12.4.1-devel-ubuntu22.04
LABEL com.nvidia.volumes.needed="nvidia_driver"

ENV PATH /usr/local/nvidia/bin:${PATH}
ENV LD_LIBRARY_PATH /usr/local/nvidia/lib:/usr/local/nvidia/lib64:${LD_LIBRARY_PATH}

# install git, python+pip and pip aws braket sdk
RUN apt update && apt install -y git python3-pip cmake build-essential && apt clean all
RUN pip3 install --upgrade pip && pip3 cache purge
RUN pip3 install amazon-braket-sdk qiskit packaging && pip3 cache purge
# pyqrack-cuda installed by source

# install build features
RUN apt-get update && apt-get -y install git build-essential cmake openssh-server wget vim-common python3-setuptools opencl-headers curl libfreetype6-dev autotools-dev libicu-dev libbz2-dev libboost-all-dev && apt-get clean all

# clone repos with qrack and providers
RUN git clone --depth=1 --recursive https://github.com/unitaryfund/qrack.git
RUN git clone --depth=1 https://github.com/unitaryfund/pyqrack.git
RUN git clone --depth=1 https://github.com/vm6502q/qiskit-qrack-provider.git 
## && cd qiskit-qrack-provider && git reset --hard 27e1ec02caa6aa0440f1fe22d070797717d0f55b && git clean -df

RUN git clone --depth=1 https://github.com/vm6502q/cirq-qrack.git

# fetch aws braket sim repos and Qrack BraKET backend repo
RUN git clone --depth=1 https://github.com/amazon-braket/amazon-braket-default-simulator-python.git
RUN git clone --depth=1 https://github.com/amazon-braket/amazon-braket-containers.git
RUN git clone --depth=1 https://github.com/amazon-braket/amazon-braket-sdk-python.git
RUN git clone --depth=1 https://github.com/amazon-braket/amazon-braket-examples.git

RUN git clone --depth=1 https://github.com/vm6502q/amazon-braket-qrack-simulator-python.git

# install qrack braket simulator + qiskit & cirq qrack-provider
RUN cd /pyqrack && pip3 install . && pip3 cache purge
RUN cd /qiskit-qrack-provider && pip3 install . && pip3 cache purge
RUN cd /cirq-qrack && pip3 install . && pip3 cache purge
RUN cd /amazon-braket-qrack-simulator-python && pip3 install . && pip3 cache purge

ENV SAGEMAKER_PROGRAM /amazon-braket-qrack-simulator-python/src/braket/qrack_simulator/qrack_simulator.py
ENTRYPOINT python3 /amazon-braket-qrack-simulator-python/src/braket/qrack_simulator/qrack_simulator.py
