FROM nvidia/cuda:12.4.1-devel-ubuntu22.04
LABEL com.nvidia.volumes.needed="nvidia_driver"
ENV PATH /usr/local/nvidia/bin:${PATH}
ENV LD_LIBRARY_PATH /usr/local/nvidia/lib:/usr/local/nvidia/lib64:${LD_LIBRARY_PATH}

# install features
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive && apt-get -y install git python3-full python3-pip python3-pybind11 build-essential cmake pocl-opencl-icd openssh-server wget vim-common python3-setuptools opencl-headers curl libfreetype6-dev autotools-dev libicu-dev libbz2-dev libboost-all-dev && apt-get clean all

# clone repos
RUN git clone --recursive --depth=1 --recursive https://github.com/unitaryfund/qrack.git
RUN git clone --recursive --depth=1 --recursive https://github.com/unitaryfund/pyqrack.git

# pyqrack examples integration
RUN git clone --recursive  --depth=1 https://github.com/vm6502q/pyqrack-examples.git

# pennylane integration
RUN git clone --recursive --depth=1 --recursive https://github.com/unitaryfund/pennylane-qrack.git
RUN git clone --recursive  --depth=1 --recursive https://github.com/PennyLaneAI/pennylane.git

# Qrack install & dependancies without OpenCL for CPU only processing
RUN cd /qrack/include && mkdir CL && cd /qrack && mkdir _build && cd _build && cmake -DENABLE_DEVRAND=ON -DFPPOW=5 -DUINTPOW=6 -DQBCAPPOW=6 -DENABLE_COMPLEX_X2=ON -DENABLE_OPENCL=OFF .. && make -i -k -j 2 all && make install

# install PyQrack
RUN cd /pyqrack &&  pip3 install .  && pip3 cache purge

# install pennylane-qrack
RUN pip3 install pennylane-catalyst pennylane-qrack && pip3 cache purge
RUN cd pennylane-qrack && mkdir _build && cd _build && cmake -DCPP_STD=14 .. && make all -j$(nproc --all) && make install

# install pennylane
RUN pip3 install pennylane && pip3 cache purge

ENTRYPOINT /qrack/_build/benchmarks --optimal-cpu
