FROM ubuntu:latest

# fetch dependancies
RUN apt update && apt install -y wget unzip curl && apt clean all

# fetch precompiled qrack benchmarks app
RUN wget https://github.com/unitaryfund/qrack/releases/download/vm6502q.v8.20.1/qrack_Ubuntu_22.04_LTS_benchmarks && chmod 744 qrack_Ubuntu_22.04_LTS_benchmarks

# fetch & install aws tools
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" &&  unzip awscliv2.zip  && ./aws/install && ./usr/local/bin/aws --version

# run qrack benchmarks test
RUN ./qrack_Ubuntu_22.04_LTS_benchmarks --optimal-cpu --measure-shots=1024 -m=-1 --samples=10 --measure-output=/var/log/qrack/"measured_qft_$(date +%F_%R_%S).log" test_qft_permutation_round_trip_entangled

# set defailt entrypoint 
ENTRYPOINT ./qrack_Ubuntu_22.04_LTS_benchmarks
